# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe2387bb44e73000c4e644b72e5986a907671927bb59a9c1393ca756fc032bc0d3925c3f19fc8c018b22e74010e33e152fdc2884620dba42209f3dfa1a67a7ec

test:
  secret_key_base: 7de32a6d52d5ffaa167b50b62eb3312b3d9a8c08e93ab87587e77cdcd8d14c3094d03f17466686a44168381c3ad1f18a873a95638aafed1d9c2902a243eb6ec5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
